const selfDevelopmentQuotes = {
  selfDevelopment:[
    "The only person you are destined to become is the person you decide to be. – Ralph Waldo Emerson",
  "Success is not final, failure is not fatal: It is the courage to continue that counts. – Winston Churchill",
  "What you do today can improve all your tomorrows. – Ralph Marston",
  "Strive not to be a success, but rather to be of value. – Albert Einstein",
  "Don’t wish it were easier. Wish you were better. – Jim Rohn",
  "You cannot dream yourself into a character; you must hammer and forge yourself one. – James A. Froude",
  "Small daily improvements over time lead to stunning results. – Robin Sharma",
  "The only way to do great work is to love what you do. – Steve Jobs",
  "Invest in yourself. Your career is the engine of your wealth. – Paul Clitheroe",
  "Be not afraid of growing slowly, be afraid only of standing still. – Chinese Proverb",
  "Discipline is the bridge between goals and accomplishment. – Jim Rohn",
  "Your life does not get better by chance, it gets better by change. – Jim Rohn",
  "He who conquers himself is the mightiest warrior. – Confucius",
  "You don’t have to be great to start, but you have to start to be great. – Zig Ziglar",
  "Become addicted to constant and never-ending self-improvement. – Anthony Robbins"
  ],
  loveQuotes :[
    "Love is composed of a single soul inhabiting two bodies. – Aristotle",
    "The best thing to hold onto in life is each other. – Audrey Hepburn",
    "Where there is love there is life. – Mahatma Gandhi",
    "You know you're in love when you can't fall asleep because reality is finally better than your dreams. – Dr. Seuss",
    "To love and be loved is to feel the sun from both sides. – David Viscott",
    "Love is not only something you feel, it is something you do. – David Wilkerson",
    "Being deeply loved by someone gives you strength, while loving someone deeply gives you courage. – Lao Tzu",
    "Love does not consist in gazing at each other, but in looking outward together in the same direction. – Antoine de Saint-Exupéry",
    "The greatest thing you'll ever learn is just to love and be loved in return. – Eden Ahbez",
    "True love begins when nothing is looked for in return. – Antoine de Saint-Exupéry",
    "Love is a friendship set to music. – Joseph Campbell",
    "To love is to recognize yourself in another. – Eckhart Tolle",
    "In the end, we discover that to love and let go can be the same thing. – Jack Kornfield",
    "Love doesn’t make the world go ’round. Love is what makes the ride worthwhile. – Franklin P. Jones",
    "There is no remedy for love but to love more. – Henry David Thoreau"
  ],
  valentineQuotes:[
    "Every love story is beautiful, but ours is my favorite. – Unknown",
    "You are my today and all of my tomorrows. – Leo Christopher",
    "I still get butterflies, even though I’ve seen you a hundred times. – Unknown",
    "I fell in love with you because of all the little things you do without even realizing. – Unknown",
    "You’re the reason I believe in love. – Unknown",
    "I didn’t choose you, my heart did. – Unknown",
    "In you, I’ve found the love of my life and my closest, truest friend. – Unknown",
    "You’re the piece I didn’t know was missing. – Unknown",
    "I look at you and see the rest of my life in front of my eyes. – Unknown",
    "You make me laugh a little louder, love a little deeper, and live a lot happier. – Unknown",
    "With you, every day feels like Valentine’s Day. – Unknown",
    "I never want to stop making memories with you. – Pierre Jeanty",
    "You’re not just my Valentine, you’re my forever. – Unknown",
    "Falling for you was the best decision I ever made. – Unknown",
    "I didn’t just fall in love with you. I stayed in love. – Unknown"
  ],
  friendshipQuotes:[
    "A friend is one who overlooks your broken fence and admires the flowers in your garden. – Unknown",
    "Friendship is born at that moment when one person says to another, ‘What! You too? I thought I was the only one.’ – C.S. Lewis",
    "True friends are never apart, maybe in distance but never in heart. – Helen Keller",
    "A real friend is one who walks in when the rest of the world walks out. – Walter Winchell",
    "Friendship isn’t about whom you’ve known the longest, it’s about who walked into your life, said 'I’m here for you,' and proved it. – Unknown",
    "There are friends, there is family, and then there are friends that become family. – Unknown",
    "Good friends are like stars. You don’t always see them, but you know they’re always there. – Christy Evans",
    "A single rose can be my garden… a single friend, my world. – Leo Buscaglia",
    "True friendship comes when the silence between two people is comfortable. – David Tyson",
    "Friendship is the only cement that will ever hold the world together. – Woodrow Wilson",
    "It’s not what we have in life, but who we have in our life that matters. – Unknown",
    "Some people arrive and make such a beautiful impact on your life, you can barely remember what life was like without them. – Anna Taylor",
    "Many people will walk in and out of your life, but only true friends will leave footprints in your heart. – Eleanor Roosevelt",
    "A sweet friendship refreshes the soul. – Proverbs 27:9",
    "Friends are the siblings God never gave us. – Mencius"
  ],
  coderQuotes:[
    "Talk is cheap. Show me the code. – Linus Torvalds",
    "First, solve the problem. Then, write the code. – John Johnson",
    "Experience is the name everyone gives to their mistakes. – Oscar Wilde",
    "Programs must be written for people to read, and only incidentally for machines to execute. – Harold Abelson",
    "Code is like humor. When you have to explain it, it’s bad. – Cory House",
    "One man’s crappy software is another man’s full-time job. – Jessica Gaston",
    "Walking on water and developing software from a specification are easy if both are frozen. – Edward V. Berard",
    "Programming isn’t about what you know; it’s about what you can figure out. – Chris Pine",
    "Good code is its own best documentation. – Steve McConnell",
    "If debugging is the process of removing software bugs, then programming must be the process of putting them in. – Edsger Dijkstra",
    "Simplicity is the soul of efficiency. – Austin Freeman",
    "The best error message is the one that never shows up. – Thomas Fuchs",
    "Make it work, make it right, make it fast. – Kent Beck",
    "In order to be irreplaceable, one must always be different. – Coco Chanel (used often by creative coders)",
    "Code never lies, comments sometimes do. – Ron Jeffries"
  ],
  designerQuotes:[
    "Design is not just what it looks like and feels like. Design is how it works. – Steve Jobs",
    "Good design is obvious. Great design is transparent. – Joe Sparano",
    "Design is thinking made visual. – Saul Bass",
    "Simplicity is the ultimate sophistication. – Leonardo da Vinci",
    "Design adds value faster than it adds costs. – Joel Spolsky",
    "The details are not the details. They make the design. – Charles Eames",
    "Design is intelligence made visible. – Alina Wheeler",
    "Creativity is intelligence having fun. – Albert Einstein",
    "Design is the silent ambassador of your brand. – Paul Rand",
    "Design is so simple, that’s why it’s so complicated. – Paul Rand",
    "People ignore design that ignores people. – Frank Chimero",
    "Good design is good business. – Thomas J. Watson",
    "If you think good design is expensive, you should look at the cost of bad design. – Dr. Ralf Speth",
    "Every designer was once a beginner. – Unknown",
    "Design is not a single object or dimension. Design is messy and complex. – Natasha Jen"
  ],
  christianQuotes:[
    "For I know the plans I have for you, declares the Lord, plans for welfare and not for evil, to give you a future and a hope. – Jeremiah 29:11",
    "The Lord is my shepherd; I shall not want. – Psalm 23:1",
    "I can do all things through him who strengthens me. – Philippians 4:13",
    "Faith is taking the first step even when you don’t see the whole staircase. – Martin Luther King Jr.",
    "Let all that you do be done in love. – 1 Corinthians 16:14",
    "God is within her, she will not fall. – Psalm 46:5",
    "For we live by faith, not by sight. – 2 Corinthians 5:7",
    "The joy of the Lord is your strength. – Nehemiah 8:10",
    "But the fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness, gentleness, and self-control. – Galatians 5:22-23",
    "Trust in the Lord with all your heart and lean not on your own understanding. – Proverbs 3:5",
    "God is love. – 1 John 4:8",
    "Where there is no vision, the people perish. – Proverbs 29:18",
    "Jesus said, ‘I am the way and the truth and the life. No one comes to the Father except through me.’ – John 14:6",
    "With God all things are possible. – Matthew 19:26",
    "Do everything in love. – 1 Corinthians 16:14"
  ],
  mothersDayQuotes:[
    "A mother's love is endless, her heart is limitless, and her care is boundless. – Unknown",
    "God could not be everywhere, and therefore he made mothers. – Rudyard Kipling",
    "A mother is she who can take the place of all others, but whose place no one else can take. – Cardinal Meymillod",
    "The influence of a mother in the lives of her children is beyond calculation. – James E. Faust",
    "To the world, you are a mother, but to your family, you are the world. – Unknown",
    "A mother’s hug lasts long after she lets go. – Unknown",
    "Life doesn’t come with a manual, it comes with a mother. – Unknown",
    "Mothers hold their children’s hands for a short while, but their hearts forever. – Unknown",
    "All that I am, or ever hope to be, I owe to my angel mother. – Abraham Lincoln",
    "Motherhood is the greatest thing and the hardest thing. – Ricki Lake",
    "There is no way to be a perfect mother, and a million ways to be a good one. – Jill Churchill",
    "A mother’s love for her child is like nothing else in the world. – Agatha Christie",
    "The heart of a mother is a deep abyss at the bottom of which you will always find forgiveness. – Honore de Balzac",
    "A mother is the one who fills your heart in the first place. – Amy Tan"
  ],
  fathersDayQuotes:[
    "A father is someone you look up to no matter how tall you grow. – Unknown",
    "Any man can be a father, but it takes someone special to be a dad. – Unknown",
    "A father’s love is forever imprinted on his children’s hearts. – Unknown",
    "The power of a dad in a child’s life is unmatched. – Justin Ricklefs",
    "Fathers are the first heroes of their sons and the first love of their daughters. – Unknown",
    "A father doesn’t tell you that he loves you. He shows you. – Dimitri the Stoneheart",
    "A father is a son’s first hero, and a daughter’s first love. – Unknown",
    "The greatest gift I ever had came from God; I call him Dad! – Unknown",
    "To the world, you are a dad. To our family, you are the world. – Unknown",
    "My father gave me the greatest gift anyone could give another person: He believed in me. – Jim Valvano",
    "Fathers, be good to your daughters. You are the God and the weight of her world. – Robert Orben",
    "A father’s job isn’t to teach you how to live. It’s to teach you how to live without him. – Unknown",
    "Dad: A son’s first hero and a daughter’s first love. – Unknown",
    "No man stands taller than when he stoops to help a child. – Abraham Lincoln",
    "A father’s love is a lifelong gift that never fades. – Unknown"
  ],
  griefQuotes:[
    "Grief is the price we pay for love. – Queen Elizabeth II",
    "To weep is to make less the depth of grief. – William Shakespeare",
    "What we have once enjoyed we can never lose. All that we love deeply becomes a part of us. – Helen Keller",
    "When someone you love becomes a memory, the memory becomes a treasure. – Unknown",
    "The pain of grief is just as much a part of life as the joy of love. – Unknown",
    "Grief never ends... but it changes. It's a passage, not a place to stay. – Unknown",
    "You don’t heal from the loss of a loved one because time passes; you heal because of what you do with the time. – Unknown",
    "The risk of love is loss, and the price of loss is grief. – Hilary Stanton Zunin",
    "Grief is not a sign of weakness, nor a lack of faith... It is the price of love. – Unknown",
    "Those we love don’t go away, they walk beside us every day. – Unknown",
    "The sorrow we feel when we lose a loved one is the price we pay to have had them in our lives. – Unknown",
    "The pain of grief is not a wound that can be healed, but rather a scar that stays with us, a reminder of our love. – Unknown",
    "Grief is like the ocean; it comes in waves, ebbing and flowing. Sometimes the water is calm, and sometimes it’s overwhelming. All we can do is learn to swim. – Vicki Harrison",
    "In the process of grieving, we slowly learn to hold on to the memories and let go of the pain. – Unknown",
    "Though nothing can bring back the hours of splendor in the grass, of glory in the flowers, we will grieve not, rather find strength in what remains behind. – William Wordsworth"
  ],
  heartbreakQuotes:[
    "The hardest part about breaking up is letting go of the dreams you had. – Unknown",
    "Sometimes the one who loves you is the one who hurts you the most. – Unknown",
    "It’s amazing how someone can break your heart, but you can still love them with all the little pieces. – Unknown",
    "A broken heart is just the growing pains necessary so that you can love more completely when the real thing comes along. – J.S.B. Morse",
    "You will find that it is necessary to let things go; simply for the reason that they are heavy. – Unknown",
    "The greatest pain that comes from love is loving someone you can never have. – Unknown",
    "You can’t be in love with someone who doesn’t love you back. – Unknown",
    "It hurts to breathe because every breath I take proves I can’t live without you. – Unknown",
    "Sometimes you have to give up on people, not because you don’t care, but because they don’t. – Unknown",
    "Love is never lost. If not reciprocated, it will flow back and soften and purify the heart. – Washington Irving",
    "It’s better to have loved and lost than never to have loved at all. – Alfred Lord Tennyson",
    "Sometimes, the person you want the most is the person you’re best without. – Unknown",
    "The scariest thing about love is that it can break you, but it’s also what heals you. – Unknown",
    "Heartbreaks are a part of life that we need to grow stronger and find the right love. – Unknown",
    "The pain of a broken heart is a reminder that we were once loved so deeply. – Unknown"
  ],
  womenEmpowermentQuotes:[
    "The most courageous act is still to think for yourself. Aloud. – Coco Chanel",
    "There is no limit to what we, as women, can accomplish. – Michelle Obama",
    "A woman is the full circle. Within her is the power to create, nurture, and transform. – Diane Mariechild",
    "I am not free while any woman is unfree, even when her shackles are very different from my own. – Audre Lorde",
    "The empowered woman is powerful beyond measure and beautiful beyond description. – Steve Maraboli",
    "You are more powerful than you know; you are beautiful just as you are. – Melissa Etheridge",
    "The future is female. – Unknown",
    "There is nothing stronger than a broken woman who has rebuilt herself. – Hannah Gadsby",
    "A girl should be two things: who and what she wants. – Coco Chanel",
    "A strong woman looks a challenge in the eye and gives it a wink. – Gina Carey",
    "Women belong in all places where decisions are being made. It shouldn’t be that women are the exception. – Ruth Bader Ginsburg",
    "When women support each other, incredible things happen. – Unknown",
    "The question isn’t who is going to let me; it’s who is going to stop me. – Ayn Rand",
    "There is no force more powerful than a woman determined to rise. – Unknown",
    "I am not free while any woman is unfree, even when her shackles are very different from my own. – Audre Lorde"
  ],
  
  
  
  
  
  
  
  
  
};



